set(CMAKE_GENERATOR_TOOLSET "ClangCL")
set(CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE "x64")

set(CPP_COMPILER_OPTIONS "-Werror=unknown-argument /std:c++17 /WX /permissive- /W4")
set(CMAKE_CXX_FLAGS_INIT ${CPP_COMPILER_OPTIONS})